export enum Environment {
    'APPLICATION_NAME' = 'NSCCC_APPLICATION_NAME',

    'BASE_URI' = 'NSCCC_BASE_URI',

    'PROFILE' = 'NSCCC_PROFILE',

    'LABEL' = 'NSCCC_LABEL',

    'FAIL_FAST' = 'NSCCC_FAIL_FAST',

    'MAX_RETRY_ATTEMPTS' = 'NSCCC_MAX_RETRY_ATTEMPTS',

    'SCALING_DURATION' = 'NSCCC_SCALING_DURATION',

    'LOGGER_ENABLED' = 'NSCCC_LOGGER_ENABLED',

    'LOGGER_LEVEL' = 'NSCCC_LOGGER_LEVEL',


}