export enum Environment {
    'APPLICATION_NAME' = 'PCCC_APPLICATION_NAME',

    'BASE_URI' = 'PCCC_BASE_URI',

    'PROFILE' = 'PCCC_PROFILE',

    'LABEL' = 'PCCC_LABEL',

    'FAIL_FAST' = 'PCCC_FAIL_FAST',

    'REQUEST_TIMEOUT' = 'PCCC_REQUEST_TIMEOUT_MS',

    'MAX_RETRY_ATTEMPTS' = 'PCCC_MAX_RETRY_ATTEMPTS',

    'SCALING_DURATION' = 'PCCC_SCALING_DURATION_MS',

    'LOGGER_ENABLED' = 'PCCC_LOGGER_ENABLED',

    'LOGGER_LEVEL' = 'PCCC_LOGGER_LEVEL',


}